### ISSUE TITLE
Needs a License.

### ISSUE THREAD

**Issue by sanscore** [jkupferman/meme-creator#2]
Could you add a license to this project? I want to add a few fun, internal single-purpose web apps at my work. I like that this project is simple and easy to modify. The only issue is that there is *no* license. Without a license, I am told by the legal team, that I am only allowed to view the source code. According to choosealicense.com, Github's ToS gives its users express permission to "fork" projects. However, that does not consent to-modify nor to-execute.

Personally, I prefer the MIT license, but for work-related OSS projects I use Apache 2.0.

* https://choosealicense.com/
* https://choosealicense.com/no-license/
* https://choosealicense.com/licenses/mit/
* https://choosealicense.com/licenses/apache-2.0/

**Comment by jkupferman** [comment]
Thanks for pointing this out. I added an MIT license in https://github.com/jkupferman/meme-creator/commit/7fb98ef10006fc7fa64b76de32903d03575eb570. 


![](http://i.imgur.com/eAsHRzr.png)

**Comment by sanscore** [comment]
Thanks!

![Success](http://memeifier.com/FILE_AN_ISSUE/MAINTAINER_RESPONDS_WITH_FIX/successkid.jpg)
